#!/usr/bin/env ruby

require "json"
require "fileutils"

puts "Deleting existing pages..."
outdir = __dir__ + "/../companion/"
FileUtils.rm_rf outdir, :verbose => true
FileUtils.mkdir_p outdir

datafiles = Dir.entries(__dir__ + "/../data")
datafiles.each do |datafile|
  next if datafile !~ /json/
  puts datafile

  section = datafile.split(".").first

  videos = JSON.parse(File.read(__dir__ + "/../data/" + datafile))
  videos.each do |video|
    key = video["key"]
    page_key = "#{section}-#{key}"
    title = video["title"]
    thumbnail = video["thumbnail"]
    premium = video["premium"]

    File.open(outdir + "/#{section}-#{video["key"]}.html", "w+") do |f|
      content = <<CONTENT
---
layout: page
key: #{key}
title: \"#{title}\"
pageKey: #{page_key}
thumbnail: #{thumbnail}
premium: #{premium}
---
CONTENT
      f.puts content
    end
  end
end

# write index page to redirect to the first home video page
content = <<CONTENT
<html>
<head>
<meta http-equiv="refresh" content="0; URL=home-0JVN2uLaY88.html" />
</head>
</html>
CONTENT

File.open(outdir + "/index.html", "w+") do |f|
  f.puts content
end
