#!/usr/bin/env ruby

require "json"
require "fileutils"

puts "Deleting existing pages..."
outdir = __dir__ + "/../companion/"
FileUtils.rm_rf outdir, :verbose => true
FileUtils.mkdir_p outdir

datafiles = Dir.entries(__dir__ + "/../data")
datafiles.each do |datafile|
  next if datafile !~ /json/
  puts datafile

  section = datafile.split(".").first
  section_outdir = "#{outdir}/#{section}"
  FileUtils.mkdir_p(section_outdir)

  videos = JSON.parse(File.read(__dir__ + "/../data/" + datafile))
  videos.each_with_index do |video, index|
    key = video["key"]
    title = video["title"]
    thumbnail = video["thumbnail"]
    premium = video["premium"]

    File.open(section_outdir + "/#{key}.html", "w+") do |f|
      content = <<CONTENT
---
layout: page
section: #{section}
key: #{key}
title: \"#{title}\"
thumbnail: #{thumbnail}
premium: #{premium}
---
CONTENT
      f.puts content
    end

    # if this is the first video, also write an index file to redirect to it
    if index == 0
      File.open(section_outdir + "/index.html", "w+") do |f|
        content = <<CONTENT
<html>
<head>
<meta http-equiv="refresh" content="0; URL=/companion/#{section}/#{key}.html" />
</head>
</html>
CONTENT
        f.puts content
      end
    end
  end
end

# write index page to redirect to the first home video page
content = <<CONTENT
<html>
<head>
<meta http-equiv="refresh" content="0; URL=/companion/home" />
</head>
</html>
CONTENT

File.open(outdir + "/index.html", "w+") do |f|
  f.puts content
end
